name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x BackEnd/project/gradlew

      - name: Build with Gradle
        working-directory: BackEnd/project
        run: ./gradlew clean build

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "BackEnd/project/build/libs/project-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/BackEnd/project/build/libs"

      - name: Execute SSH Commands on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Uploaded JAR 확인:"
            ls -lh /home/ubuntu/project-0.0.1-SNAPSHOT.jar

            echo "Spring Boot 프로세스 종료 시도..."
            screen -S spring-server -X quit || true

            echo "Spring Boot 새 screen 세션으로 실행..."
            screen -dmS spring-server java -jar /home/ubuntu/project-0.0.1-SNAPSHOT.jar