name: Deploy React Frontend to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 필요에 따라 버전 조정 18 -> 22로 변경함

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React app
        run: npm run build
        working-directory: ./frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v1
        with:
          source-dir: ./frontend/build
          bucket: project-bucbucket
          args: --delete
      
      # - name: Invalidate CloudFront cache (optional)
      #   if: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #   uses: chetan/invalidate-cloudfront-action@v1
      #   with:
      #     distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #     paths: '/*'
      #     aws-region: ap-northeast-2
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}